### ISSUE TITLE
add browserify plugin

### ISSUE THREAD

**Issue by LinusU** [sighjs/sigh#2]
I'm trying to figure out how to use this together with [browserify](https://github.com/substack/node-browserify).

It needs to resolve the files itself so I'm not really sure how that would tie in to the rest, and how to have the watch function work.

**Comment by ohjames** [comment]
Thanks for opening this issue, browserify support is definitely something I want to support.

I'm giving a presentation on sigh in three weeks where I'll be demonstrating a flow involving `jspm` so that's where my focus has been currently (I'm about to publish a blog article showing some great things you can do with these two things in combination).

I'd be really happy to help you in any way though if you want to work on this feature before I have the time to start it properly.

Ideally browserify would let us pass in a "virtual filesystem" (i.e. just an object where the keys are file paths and the values are the file content) and that flow would be easy to support with the way sigh currently works.

If not, my other idea is to add a stream adapter into `sigh-core` that will simply recreate the events streamed in as real files (+ source maps) in a temporary directory. Then you could easily invoke browserify as you do now with a full filesystem tree (I assume browserify will take the input source maps and apply it's own source maps on top... if not this could be worked around in the plugin fairly easily using the source map helper module in sigh-core).

This stream adapter would then also be great for other plugins to use that also need access to a filesystem.

**Comment by LinusU** [comment]
I won't have time to have a look at this for my current project, but hopefully I will find some time on weekends or nights. Sigh looks very promising so far!

**Comment by ohjames** [comment]
Thanks! In three weeks I'll have time to look at this myself. I'd also encourage you to check out JSPM if you haven't already, I think in the future it will be much more prevalent than bower/browserify.

**Comment by troch** [comment]
I am interested in hearing about jspm with sighjs.

**Comment by ohjames** [comment]
Here's a `sigh.js` I'm using on a `jspm` project:

```javascript
var merge, env, debounce, glob, concat, write, babel, uglify

module.exports = function(pipelines) {
  pipelines.build = [
    merge(
      [ glob({ basePath: 'src' }, '*.js'), babel({ modules: 'system' }) ],
      env(glob('lib/livereload.js'), 'development')
    ),
    debounce(50),
    concat('init.js'),
    env(/* jspmBundle(), */ uglify(), 'production'),
    write({ clobber: '!(jspm_packages)' }, 'client/build'),
    livereload()
  ]
}
```

With this you get all of the advantages of incremental rebuilds together with the goodness jspm brings.

Writing the `jspm bundle` plugin is blocked by https://github.com/systemjs/builder/issues/163 so until then it's still better to use `jspm bundle` for production builds, after that bug is fixed you'll be able to handle it faster with `sigh -e production`.

One thing worth noting is I have this in my package.json:

```javascript
  "jspm": {
    "directories": {
      "baseURL": "client/build"
    },
    "configFile": "client/config.js",
```

And this in my `client/config.js`:

```javascript
System.config({
  "baseURL": "build",
```

Those settings let me keep the directory structure cleaner.

**Comment by ohjames** [comment]
@tcroch Oh and that `sigh.js` will also get you really fast livereload support together with your incremental rebuilds. To get the required sigh/gulp plugins:

`npm install --save-dev sigh-babel sigh-livereload gulp-uglify`

This is what I have in my `index.html`:

```html
    <script src="build/jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>System.import('init')</script>
```

**Comment by ohjames** [comment]
Here's the contents of `lib/livereload.js` in case you're interested:

```javascript
var js = document.createElement('script')
js.src = '//' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1'
document.body.appendChild(js)
```

That sigh configuration there will add that snippet onto the end of your `init.js` file in your development builds. (`sigh -e development` === `sigh`).

**Comment by troch** [comment]
Thanks, I'll give it a shot on a project.

**Comment by ohjames** [comment]
@troch Feel free to tweet me/e-mail me if you have any questions or want any support, I've got some time off this week to work on a sigh presentation and to add more features to sigh so I'd be happy to help!

**Comment by ohjames** [comment]
Made it mega-easy to create new sigh-plugins with the latest sigh-cli, see https://github.com/sighjs/sigh/blob/master/docs/writing-plugins.md

**Comment by Globegitter** [comment]
We are only using npm as our package manager via browserify. JSPM does look interesting and I may be inclined to use it but right now I am also quiet interested in browserify support since I want to make a comparison of broccoli vs. gulp vs sigh vs. our current build-system to see how much speed we can gain and which one just works nicer. All that combined with browser-sync rather than livereload. 

I might be inclined to write a sigh-browser-sync plugin myself, since I have to do the same for broccoli anyway but Broccoli does seem to have a very nice browserify plugin already.

**Comment by ohjames** [comment]
Changelog is a good idea, created an issue for it (#5).

I definitely would like to make a browserify plugin, at the moment though I'm concentrating my efforts on working with the jspm/systemjs guys. It may be some time before I get around to writing `sigh-browserify` but I'd be happy to mentor anybody who has a stronger need for it. It should be pretty easy to add though, I'd probably use the [toFilesystemState](https://github.com/sighjs/sigh-core/blob/master/src/stream.js#L66) utility provided by `sigh-core`, this can be used to convert a stream of events into an object representing the most recent whole filesystem state which the browserify plugin would need. This utility is used in the [concatentation plugin](https://github.com/sighjs/sigh/blob/master/src/plugin/concat.js#L10).

**Comment by ohjames** [comment]
Oh and I [added an issue](https://github.com/sighjs/sigh/issues/6) for the browsersync plugin, writing it should be really easy, we can discuss it further there.

**Comment by troch** [comment]
For changelog management, you can use [conventional-changelog](https://www.npmjs.com/package/conventional-changelog). It requires to write commit messages following specific guidelines (a few preset are available: angular, jquery, ...) but then it generates your changelog beautifully.

**Comment by ohjames** [comment]
After looking at the watchify source code I've decided I'll be able to quickly write a browserify plugin at the weekend. As long as I'm recovered from this damned flu ;) :baby_chick:

**Comment by ohjames** [comment]
```
b.require({  entry: true, expose: false, file: filename, source: sourceCodeString })
b.bundle().pipe(concat(function(buf) { ... }))
```

**Comment by ohjames** [comment]
You sure learn a lot about browserify internals by seeing how watchify accesses the private fields. Couldn't work out how the hell the cache was working until I discovered that the `module-deps` module dependency is the one that uses it. So watchify reaches into browserify internal state that isn't used by browserify but a transitive dependency. NICE ;)

**Comment by ohjames** [comment]
Needs a change to one of browserify's dependencies to work, more information in the ticket there: https://github.com/substack/module-deps/pull/94

Hopefully they'll accept the PR, or not take ages to accept it. It's only a 5 character change. Blocked until they accept that.

**Comment by ohjames** [comment]
The reason broccoli can easily support browserify is because in broccoli "the filesystem is the API." This to me, is very questionable. I could just pipe out the in-memory data to the filesystem to support browserify as it stands now, but I really don't want to do that.

**Comment by ohjames** [comment]
Added a changelog, can't progress the browserify plugin as the browserify guys haven't responded to [my pull request](https://github.com/substack/module-deps/pull/94) yet. The browserify code makes me feel even stronger that jspm is the superior option. The code is barely documented at all and they have a penchant for giving variables silly names like `c` and `n`.

**Comment by Globegitter** [comment]
@ohjames thanks for the efforts so far, much appreciated. Jspm is now definitely on my list of things to try.

**Comment by ohjames** [comment]
@Globegitter I'm working on a yeoman "sigh-jspm-fullstack" generator that uses HTTP2 greatness for development workflows. `jspm` has some drawbacks when used as recommend due to the lack of a transpiler cache (on every reload every ES6 source file is retranspiled leading to delays performing unnecessary repeated work). However of course with sigh we can work around that and produce pre-transpiled output for JSPM server-side using multiple CPUs.

With this configuration sigh+jspm blows gulp/broccoli+browserify out of the water IMO :)

**Comment by ohjames** [comment]
@Globegitter Added the `browser-sync` plugin: https://github.com/sighjs/sigh-browser-sync

Been using it on a project, really nice, guess I don't need livereload anymore then.

**Comment by ohjames** [comment]
Been working with the browserify people for a while tonight, ultimately doesn't look like browserify can work from the filesystem. If anybody is interested enough it wouldn't be difficult to get a `sigh-browserify` plugin to pipe it's in memory data out to the filesystem so browserify can access it. I'm going to concentrate on `jspm` and other areas instead for now.

**Comment by ohjames** [comment]
Added an issue to `sigh-core` https://github.com/sighjs/sigh-core/issues/1 to write an API so that fs-only APIs can be used easily from sigh.

**Comment by Globegitter** [comment]
Thanks for the updates! Definitely considering jspm but first I do want to get everything working with our custom build system in a backwards-compatible manner which is already taking some effort. 

Also I just saw that you managed to get part of that PR in: https://github.com/substack/module-deps/pull/95 So does that mean that browserify will now work from memory?

**Comment by ohjames** [comment]
@Globegitter Haha yeah after all this I got the PR in, and I think I can make browserify work from memory after all by passing in a custom resolver that is aware of the `fileCache`. I probably won't have time to work on it until next weekend now though, dayjob stuff :( :baby_chick:

**Comment by unlight** [comment]
Any updates?

**Comment by ohjames** [comment]
I won't be working on a browserify plugin myself, unless anyone else volunteers I'll close this.
